-- ============================================================
-- Migration 011 — Trainer contact details
-- ePawatech — Stage 2
-- ============================================================
-- A trainer's login email remains in auth.users, which is the only source of
-- truth for authentication. phone_number is optional at database level so
-- admin-created/imported profiles remain possible, but trainer self-signup
-- requires it in the application.

ALTER TABLE profiles
  ADD COLUMN phone_number TEXT;

ALTER TABLE profiles
  ADD CONSTRAINT chk_profiles_phone_number_format
  CHECK (
    phone_number IS NULL
    OR phone_number ~ '^\+[1-9][0-9]{7,14}$'
  );

COMMENT ON COLUMN profiles.phone_number IS
  'Optional contact phone in E.164 format, for example +254712345678. '
  'Required by the trainer self-signup form but nullable for administrative imports.';

-- Preserve 010's student username logic and include the trainer contact value
-- in every new profile generated by the auth.users trigger.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  requested_role TEXT := COALESCE(NEW.raw_user_meta_data ->> 'requested_role', 'student');
  requested_username TEXT := upper(trim(COALESCE(NEW.raw_user_meta_data ->> 'username', '')));
  requested_phone_number TEXT := NULLIF(trim(COALESCE(NEW.raw_user_meta_data ->> 'phone_number', '')), '');
BEGIN
  IF requested_role = 'student'
     AND requested_username !~ '^[A-Z][A-Z0-9-]{2,29}$' THEN
    RAISE EXCEPTION 'Student username must be 3–30 characters: A–Z, numbers, and hyphen; it must start with a letter'
      USING ERRCODE = '22023';
  END IF;

  IF requested_phone_number IS NOT NULL
     AND requested_phone_number !~ '^\+[1-9][0-9]{7,14}$' THEN
    RAISE EXCEPTION 'Phone number must use E.164 format, for example +254712345678'
      USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.profiles (id, full_name, username, phone_number, role, status)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', ''),
    CASE WHEN requested_role = 'student' THEN requested_username ELSE NULL END,
    CASE WHEN requested_role = 'trainer' THEN requested_phone_number ELSE NULL END,
    CASE WHEN requested_role = 'trainer' THEN 'trainer'::app_role ELSE 'student'::app_role END,
    CASE WHEN requested_role = 'trainer' THEN 'pending'::profile_status ELSE 'active'::profile_status END
  );
  RETURN NEW;
END;
$$;
